spring.application.name=gestao

# ============================================================
# MongoDB Atlas - substitua pela sua connection string
# ============================================================
spring.data.mongodb.uri=
spring.mongodb.uri=

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# Servidor
server.port=8080

# Mostrar detalhes do erro no browser para debug
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-exception=true
